# conda env create --file environment.yml
# mamba env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - pyspark
  - python={{ cookiecutter.python_version }}
  - python-dotenv
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow
  {% if cookiecutter.project_packages == "All" %}
  - keras
  - lightgbm
  - missingno
  - pandas-flavor
  - pandas-profiling
  - pylint
  - pyspark
  - python-dotenv
  - scikit-learn
  - statsmodels
  - tensorflow
  {% endif %}
